export type PoCompanyProfile = {
  name: string;
  addressLine1: string;
  addressLine2: string;
  phone: string;
};

export function getPoCompanyProfile(): PoCompanyProfile {
  return {
    name:
      process.env.PO_COMPANY_NAME ??
      process.env.COMPANY_NAME ??
      "Tropical Battery Company Limited",
    addressLine1:
      process.env.COMPANY_ADDRESS_LINE1 ??
      "30 Automotive Parkway, Ferry Commercial Park",
    addressLine2:
      process.env.COMPANY_ADDRESS_LINE2 ??
      "Kingston 20, Kingston, Jamaica",
    phone: process.env.COMPANY_PHONE ?? "Tel: (876) 923-6231",
  };
}

export function getPoCompanyName(): string {
  return getPoCompanyProfile().name;
}

export function getTenantPrefix(): string {
  return process.env.TENANT_PREFIX ?? "TB";
}

export function getPoFromEmail(): string | null {
  return process.env.PO_FROM_EMAIL ?? null;
}

export function getInternalPoRecipientEmail(): string | null {
  return process.env.INTERNAL_PO_RECIPIENT_EMAIL ?? null;
}

export function getResendApiKey(): string | null {
  return process.env.RESEND_API_KEY ?? null;
}

export function getPoPdfFooterLabel(): string {
  return (
    process.env.PO_PDF_FOOTER_LABEL ??
    "Generated by Inventory Intelligence Platform - Tropical Battery Pilot"
  );
}
