"use client";

import { ChevronDown, ChevronRight, Clock, RefreshCw, Sparkles } from "lucide-react";
import { useMemo, useState, useTransition } from "react";
import { fetchReorderPortfolioSummary } from "@/app/(main)/reorder/ai-actions";
import { AiFormattedText } from "@/components/reorder/ai-formatted-text";
import { buildPortfolioSummaryPayload } from "@/lib/ai/portfolio-summary";
import { Card } from "@/components/ui/Card";
import type { ReorderRecommendation, VelocityDiagnostic } from "@/lib/types";

type AiSummaryPanelProps = {
  filteredRecommendations: ReorderRecommendation[];
  diagnosticsBySku: Record<string, VelocityDiagnostic>;
  filterDescription: string;
};

function sourceLabel(source: "ai" | "cache" | "fallback"): string {
  switch (source) {
    case "ai":
      return "Generated by AI";
    case "cache":
      return "Cached AI summary";
    case "fallback":
      return "AI unavailable (template summary)";
  }
}

export function AiSummaryPanel({
  filteredRecommendations,
  diagnosticsBySku,
  filterDescription,
}: AiSummaryPanelProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const [source, setSource] = useState<"ai" | "cache" | "fallback" | null>(
    null
  );
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const diagnosticsMap = useMemo(() => {
    return new Map(Object.entries(diagnosticsBySku));
  }, [diagnosticsBySku]);

  function handleGenerateSummary(bypassCache = false) {
    setErrorMessage(null);

    startTransition(async () => {
      try {
        const payload = buildPortfolioSummaryPayload(
          filteredRecommendations,
          diagnosticsMap,
          filterDescription
        );
        const result = await fetchReorderPortfolioSummary(payload, bypassCache);
        setSummary(result.summary);
        setSource(result.source);
      } catch {
        setErrorMessage("Could not generate summary. Please try again.");
      }
    });
  }

  return (
    <Card className="border-[#FCA5A5] bg-tbc-red-light p-0">
      <button
        type="button"
        onClick={() => setIsOpen((current) => !current)}
        className="flex w-full items-center justify-between px-6 py-4 text-left"
      >
        <div className="flex items-start gap-3">
          <Sparkles className="mt-0.5 h-5 w-5 text-tbc-red" aria-hidden="true" />
          <div>
            <p className="font-semibold text-slate-900">AI Summary</p>
            <p className="text-sm text-slate-600">
              Portfolio narrative from current filters (on demand)
            </p>
          </div>
        </div>
        {isOpen ? (
          <ChevronDown className="h-5 w-5 text-slate-500" aria-hidden="true" />
        ) : (
          <ChevronRight className="h-5 w-5 text-slate-500" aria-hidden="true" />
        )}
      </button>

      {isOpen ? (
        <div className="border-t border-[#FCA5A5] px-6 py-4">
          {!summary ? (
            <div className="flex flex-wrap items-center gap-3">
              <button
                type="button"
                onClick={() => handleGenerateSummary(false)}
                disabled={isPending || filteredRecommendations.length === 0}
                className="rounded-lg bg-tbc-red px-4 py-2 text-sm font-medium text-white hover:bg-tbc-red-hover disabled:cursor-not-allowed disabled:opacity-60"
              >
                {isPending ? "Generating..." : "Generate AI summary"}
              </button>
              {filteredRecommendations.length === 0 ? (
                <p className="text-sm text-slate-600">
                  No items in the current filter to summarize.
                </p>
              ) : null}
            </div>
          ) : null}

          {errorMessage ? (
            <p className="mt-3 text-sm text-red-600">{errorMessage}</p>
          ) : null}

          {summary ? (
            <div className="rounded-lg border border-[#FCA5A5] bg-white p-4">
              <div className="mb-3 flex items-start justify-end gap-2">
                {source ? (
                  <span className="inline-flex items-center gap-1 text-xs italic text-slate-400">
                    <Clock className="h-3 w-3" aria-hidden="true" />
                    {sourceLabel(source)}
                  </span>
                ) : null}
                <button
                  type="button"
                  onClick={() => handleGenerateSummary(true)}
                  disabled={isPending || filteredRecommendations.length === 0}
                  className="inline-flex items-center gap-1 rounded-md border border-slate-200 bg-white px-2 py-1 text-xs font-medium text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"
                  title="Regenerate summary"
                >
                  <RefreshCw
                    className={`h-3 w-3 ${isPending ? "animate-spin" : ""}`}
                    aria-hidden="true"
                  />
                  Regenerate
                </button>
              </div>

              {isPending ? (
                <div className="space-y-2" aria-hidden="true">
                  <div className="h-3 w-full animate-pulse rounded bg-slate-200" />
                  <div className="h-3 w-11/12 animate-pulse rounded bg-slate-200" />
                  <div className="h-3 w-4/5 animate-pulse rounded bg-slate-200" />
                </div>
              ) : (
                <AiFormattedText text={summary} />
              )}
            </div>
          ) : null}
        </div>
      ) : null}
    </Card>
  );
}
