"use client";

import Link from "next/link";
import { useEffect, useState, useTransition } from "react";
import { fetchReorderItemExplanation } from "@/app/(main)/reorder/ai-actions";
import type { ReorderRecommendation } from "@/lib/types";

type ExplainPanelProps = {
  rec: ReorderRecommendation;
  onClose: () => void;
};

function sourceLabel(source: "ai" | "cache" | "fallback"): string {
  switch (source) {
    case "ai":
      return "Generated by AI";
    case "cache":
      return "Cached AI explanation";
    case "fallback":
      return "AI unavailable (template explanation)";
  }
}

export function ExplainPanel({ rec, onClose }: ExplainPanelProps) {
  const [explanation, setExplanation] = useState<string | null>(null);
  const [dataGaps, setDataGaps] = useState<string[]>(rec.dataGaps);
  const [source, setSource] = useState<"ai" | "cache" | "fallback" | null>(
    null
  );
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  useEffect(() => {
    setExplanation(null);
    setSource(null);
    setErrorMessage(null);
    setDataGaps(rec.dataGaps);

    startTransition(async () => {
      try {
        const result = await fetchReorderItemExplanation(rec.sku);
        setExplanation(result.explanation);
        setSource(result.source);
        setDataGaps(result.dataGaps);
      } catch {
        setErrorMessage("Could not load explanation. Please try again.");
      }
    });
  }, [rec]);

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/30">
      <div
        role="dialog"
        aria-modal="true"
        className="h-full w-full max-w-md overflow-y-auto border-l border-slate-200 bg-white p-6 shadow-xl"
      >
        <div className="flex items-start justify-between gap-4">
          <div>
            <h3 className="text-lg font-semibold text-slate-900">
              Reorder explanation
            </h3>
            <p className="mt-1 text-sm text-slate-600">{rec.sku}</p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-2xl border border-transparent shadow-card px-2 py-1 text-sm text-slate-600 hover:bg-slate-50"
          >
            Close
          </button>
        </div>

        {isPending ? (
          <p className="mt-6 text-sm text-slate-600">Generating explanation...</p>
        ) : null}

        {errorMessage ? (
          <p className="mt-6 text-sm text-red-600">{errorMessage}</p>
        ) : null}

        {explanation ? (
          <>
            <p className="mt-6 text-sm leading-6 text-slate-700">{explanation}</p>
            {source ? (
              <p className="mt-3 text-xs text-slate-500">{sourceLabel(source)}</p>
            ) : null}
          </>
        ) : null}

        {dataGaps.length > 0 ? (
          <div className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-4">
            <p className="text-sm font-medium text-amber-900">Data gaps</p>
            <ul className="mt-2 list-disc space-y-1 pl-4 text-sm text-amber-800">
              {dataGaps.map((gap) => (
                <li key={gap}>{gap}</li>
              ))}
            </ul>
          </div>
        ) : null}

        <Link
          href="/reference-data"
          className="mt-6 inline-flex text-sm font-medium text-accent hover:text-accent-hover"
        >
          Review reference data
        </Link>
      </div>
    </div>
  );
}
